roasts = [
    "You're so slow, you'd lose a race with a statue.",
    "I'd agree with you, but then we'd both be wrong.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "You have a face for radio.",
    "I'd tell you to go outside and play, but I'm afraid you'd melt.",
    "You're the reason they put instructions on shampoo bottles.",
    "If I had a dollar for every smart thing you say, I'd be broke.",
    "You're so dense, light bends around you.",
    "I'm not insulting you, I'm describing you.",
    "You're about as useful as a screen door on a submarine.",
    "Did your parents ever ask you to run away from home?",
    "I'd love to see things from your point of view, but I can't seem to get my head that far up my rear.",
    "If you were any more inbred, you'd be a sandwich.",
    "Your family tree must be a cactus because everyone on it is a prick.",
    "You're so ugly, Hello Kitty said goodbye to you.",
    "You're so dumb, you think Taco Bell is a Mexican phone company.",
    "I'm jealous of people who don't know you.",
    "You bring everyone so much joy... when you leave the room.",
    "I'd explain it to you, but I don't have any crayons with me.",
    "You're like Monday mornings, nobody likes you.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "I'm not saying you're stupid, I'm just saying you've got bad luck when it comes to thinking.",
    "If you were twice as smart, you'd still be stupid.",
    "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
    "The last thing I want to do is hurt you. But it's still on my list.",
    "If you were any less intelligent we'd have to water you twice a week.",
    "It's better to let someone think you are an idiot than to open your mouth and prove it.",
    "If you were any more inbred you'd be a sandwich.",
    "You're so ugly, you scared the crap out of the toilet.",
    "Your birth certificate is an apology letter from the condom factory.",
    "I guess you prove that even god makes mistakes sometimes.",
    "The only way you'll ever get laid is if you crawl up a chicken's butt and wait.",
    "You're so fake, Barbie is jealous.",
    "I'm sorry, was I meant to be offended? The only thing offending me is your face.",
    "You're so fat, you could sell shade.",
    "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
    "Don't you love nature, despite what it did to you?",
    "You are so old, when you were a kid rainbows were black and white.",
    "If you really want to know about mistakes, you should ask your parents.",
    "You're so fat, you've got more chins than a Hong Kong phone book.",
    "I would ask how old you are but I know you can't count that high.",
    "You're so ugly, when you popped out the doctor said 'Aww what a treasure' and your mom said 'Yeah, let's bury it.'",
    "You're so fat, your belly button gets home 15 minutes before you do.",
    "You're so stupid you tried to wake a sleeping bag.",
    "You're so ugly you make blind kids cry.",
    "You're the reason the gene pool needs a lifeguard.",
    "If brains were dynamite you wouldn't have enough to blow your nose.",
    "Your parents hated you so much your bath toys were an iron and a toaster.",
    "You are so ugly that when your mama dropped you off at school she got a fine for littering.",
    "You're so ugly you could make a train take a dirt road.",
    "You're so fat you need cheat codes to play Wii Fit.",
    "You're so ugly, you scared the crap out of the toilet.",
    "Your family tree must be a cactus because everybody on it is a prick.",
    "You're so fat, when you fell I didn't laugh, but the sidewalk cracked up.",
    "You're so ugly, when you threw a boomerang it didn't come back.",
    "You're so fat, when you go camping the bears hide their food.",
    "You're so fat, if you got your shoes shined, you'd have to take their word for it.",
    "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're so ugly, you could make a freight train take a dirt road.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "I'd agree with you but then we'd both be wrong.",
    "You're so fat, you could sell shade.",
    "Your birth certificate is an apology letter from the condom factory.",
    "You're so ugly, Hello Kitty said goodbye to you.",
    "You're so fat, when you wear a yellow raincoat people scream 'Taxi!'",
    "You're so stupid, you'd trip over a cordless phone.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "You're so ugly, you make blind kids cry.",
    "You're so fat, you've got more chins than a Hong Kong phone book.",
    "You're so old, your birth certificate expired.",
    "You're so ugly, when you look in the mirror your reflection looks away.",
    "You're so stupid, you think Taco Bell is a Mexican phone company.",
    "You're so ugly, when you were born the doctor slapped your mother.",
    "You're so fat, your shadow weighs 35 pounds.",
    "You're so ugly, when you walk into a bank, they turn off the cameras.",
    "You're so stupid, it takes you an hour to cook minute rice.",
    "You're so ugly, your portraits hang themselves.",
    "You're so fat, when you fell I didn't laugh, but the sidewalk cracked up.",
    "You're so old, your first Christmas was a white Christmas.",
    "You're so ugly, you could make a happy meal cry.",
    "You're so stupid, you tried to climb Mountain Dew.",
    "You're so ugly, when you were born, your mother said, 'What a treasure!' and your father said, 'Yes, let's go bury it.'",
    "You're so fat, you don't need internet, you're already worldwide.",
    "You're so old, you walked into an antique shop and they kept you.",
    "You're so ugly, you could scare the chrome off a bumper.",
    "You're so stupid, you thought a quarterback was a refund.",
    "You're so ugly, when you went to a haunted house you came out with a job application.",
    "You're so fat, when you go to the movies, you sit next to everyone.",
    "You're so old, your social security number is 1.",
    "You're so ugly, your mom had to tie a steak around your neck to get the dog to play with you.",
    "You're so stupid, you stared at a cup of orange juice for 12 hours because it said 'concentrate'.",
    "You're so ugly, when you were born the doctor threw you out the window and the window threw you back.",
    "You're so slow, even snails give you a head start.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "You're like a software update, nobody wants you but everyone is forced to deal with you.",
    "You're so forgettable, even your shadow leaves you.",
    "You're the human equivalent of a participation trophy.",
    "You're so awkward, even your reflection avoids eye contact.",
    "You're like a broken pencil, pointless.",
    "You're so bland, even water has more flavor.",
    "You're the reason the gene pool needs a lifeguard.",
    "You're so lazy, you make a sloth look like an Olympic athlete.",
    "You're like a cloud, when you disappear, it's a brighter day.",
    "You're so dull, even a butter knife is sharper.",
    "You're the reason why the middle finger was invented.",
    "You're so clueless, you couldn't find your way out of a paper bag.",
    "You're like a candle in the wind, easily blown out.",
    "You're so basic, even a plain bagel has more personality.",
    "You're the human version of a typo.",
    "You're so irrelevant, even history forgot you.",
    "You're like a WiFi signal, weak and unreliable.",
    "You're so out of touch, even your GPS can't find you.",
    "You're the reason why people lock their doors.",
    "You're so transparent, even glass is more opaque.",
    "You're like a speed bump, just in the way.",
    "You're so outdated, even dinosaurs are more current.",
    "You're the human equivalent of a dead battery.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a bad haircut, everyone notices but no one says anything.",
    "You're so insignificant, even ants overlook you.",
    "You're the reason why people double-check their locks.",
    "You're so invisible, even ghosts can't see you.",
    "You're like a rerun, predictable and boring.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the human version of a 404 error.",
    "You're so forgettable, even your memories forget you.",
    "You're like a flat tire, deflated and useless.",
    "You're so uninspiring, even a blank page is more motivating.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're like a lighthouse in the desert, bright but useless.",
    "You're so out of touch, even your shadow left you.",
    "You're like a dictionary with no words, empty and pointless.",
    "You're so uninspiring, even a blank canvas is more exciting.",
    "You're the reason why people need noise-canceling headphones.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken compass, always lost.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten bookmark, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a WiFi signal, weak and unreliable.",
    "You're so out of touch, even your GPS can't find you.",
    "You're the reason why people lock their doors.",
    "You're so transparent, even glass is more opaque.",
    "You're like a speed bump, just in the way.",
    "You're so outdated, even dinosaurs are more current.",
    "You're the human equivalent of a dead battery.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a bad haircut, everyone notices but no one says anything.",
    "You're so insignificant, even ants overlook you.",
    "You're the reason why people double-check their locks.",
    "You're so invisible, even ghosts can't see you.",
    "You're like a rerun, predictable and boring.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the human version of a 404 error.",
    "You're so forgettable, even your memories forget you.",
    "You're like a flat tire, deflated and useless.",
    "You're so uninspiring, even a blank page is more motivating.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless.",
    "You're so unnoticeable, even your reflection ignores you.",
    "You're the reason why people need coffee.",
    "You're so unmemorable, even your name tag forgets you.",
    "You're like a bad joke, nobody laughs.",
    "You're so unimportant, even your shadow leaves you.",
    "You're the human version of a buffering video.",
    "You're so unremarkable, even your shadow leaves you.",
    "You're like a forgotten password, nobody remembers you.",
    "You're so unoriginal, even your echo is tired of you.",
    "You're the reason why people need vacations.",
    "You're so unimportant, even your shadow leaves you.",
    "You're like a broken record, repetitive and annoying.",
    "You're so uninteresting, even your dreams are bored.",
    "You're the human equivalent of a spam email.",
    "You're so out of place, even a fish out of water fits in better.",
    "You're like a dull pencil, pointless."
]

print(len(roasts))